/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.adservices.service.measurement.aggregation;

import com.android.adservices.service.Flags;
import com.android.adservices.service.measurement.FilterMap;
import com.android.adservices.service.measurement.Source;
import com.android.adservices.service.measurement.Trigger;
import com.android.adservices.service.measurement.XNetworkData;
import com.android.adservices.service.measurement.util.Filter;
import com.android.adservices.service.measurement.util.UnsignedLong;
import com.android.internal.annotations.VisibleForTesting;

import org.json.JSONException;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.TreeMap;
import java.util.stream.IntStream;

/**
 * Class used to generate AggregateReport using AggregatableAttributionSource and
 * AggregatableAttributionTrigger.
 */
public class AggregatePayloadGenerator {
    private final Flags mFlags;
    @VisibleForTesting
    public static final String PRE_FLEXIBLE_CONTRIBUTION_FILTERING_API_VERSION = "0.1";

    @VisibleForTesting
    public static final String POST_FLEXIBLE_CONTRIBUTION_FILTERING_API_VERSION = "1.0";

    public AggregatePayloadGenerator(Flags flags) {
        mFlags = flags;
    }

    /**
     * Generates the {@link AggregateReport} from given AggregatableAttributionSource and
     * AggregatableAttributionTrigger.
     *
     * @param source the aggregate attribution source used for aggregation.
     * @param trigger the aggregate attribution trigger used for aggregation.
     * @return the aggregate report generated by the given aggregate attribution source and
     *     aggregate attribution trigger.
     */
    public Optional<List<AggregateHistogramContribution>> generateAttributionReport(
            Source source, Trigger trigger) throws JSONException {
        Optional<AggregatableAttributionSource> aggregateAttributionSource =
                source.getAggregatableAttributionSource(trigger, mFlags);
        Optional<AggregatableAttributionTrigger> aggregateAttributionTrigger =
                trigger.getAggregatableAttributionTrigger(mFlags);
        if (aggregateAttributionSource.isEmpty() || aggregateAttributionTrigger.isEmpty()) {
            return Optional.empty();
        }

        AggregatableAttributionSource attributionSource = aggregateAttributionSource.get();
        AggregatableAttributionTrigger attributionTrigger = aggregateAttributionTrigger.get();

        FilterMap sourceFilterMap = attributionSource.getFilterMap();
        TreeMap<String, BigInteger> aggregateSourceMap =
                attributionSource.getAggregatableSource();
        Filter filter = new Filter(mFlags);
        for (AggregateTriggerData triggerData : attributionTrigger.getTriggerData()) {
            Optional<List<FilterMap>> filterSet = triggerData.getFilterSet();
            Optional<List<FilterMap>> notFilterSet = triggerData.getNotFilterSet();
            // Skip this trigger data when filter doesn't match.
            if (filterSet.isPresent()
                    && !filter.isFilterMatch(sourceFilterMap, filterSet.get(), true)) {
                continue;
            }
            // Skip this trigger data when not_filters doesn't match.
            if (notFilterSet.isPresent()
                    && !filter.isFilterMatch(sourceFilterMap, notFilterSet.get(), false)) {
                continue;
            }

            final BigInteger triggerDataKey;
            Optional<BigInteger> keyMappingForAdtech =
                    Optional.ofNullable(trigger.parseAdtechKeyMapping())
                            // Derived source has parent source's enrollment ID
                            .map(map -> map.get(source.getEnrollmentId()));
            if (source.getParentId() != null && keyMappingForAdtech.isPresent()) {
                int keyOffset =
                        triggerData
                                .getXNetworkData()
                                .flatMap(XNetworkData::getKeyOffset)
                                .map(UnsignedLong::getValue)
                                .map(Long::intValue)
                                .orElse(0);

                BigInteger orValue = keyMappingForAdtech.get().shiftLeft(keyOffset);
                triggerDataKey = triggerData.getKey().or(orValue);
            } else {
                triggerDataKey = triggerData.getKey();
            }

            for (String sourceKey : triggerData.getSourceKeys()) {
                aggregateSourceMap.computeIfPresent(sourceKey, (k, v) -> v.or(triggerDataKey));
            }
        }

        List<AggregateHistogramContribution> contributions = new ArrayList<>();
        Optional<Map<String, AggregatableKeyValue>> maybeMatchedValueMap =
                getMatchedAggregatableKeyValueMap(attributionTrigger, sourceFilterMap, filter);
        if (maybeMatchedValueMap.isPresent()) {
            for (String id : aggregateSourceMap.navigableKeySet()) {
                if (maybeMatchedValueMap.get().containsKey(id)) {
                    if (mFlags.getMeasurementEnableFlexibleContributionFiltering()) {
                        UnsignedLong filteringId = UnsignedLong.ZERO;
                        if (maybeMatchedValueMap.get().get(id).getFilteringId() != null) {
                            filteringId = maybeMatchedValueMap.get().get(id).getFilteringId();
                        }
                        contributions.add(
                                buildContribution(
                                        aggregateSourceMap.get(id),
                                        maybeMatchedValueMap.get().get(id).getValue(),
                                        filteringId));
                    } else {
                        contributions.add(
                                buildContribution(
                                        aggregateSourceMap.get(id),
                                        maybeMatchedValueMap.get().get(id).getValue()));
                    }
                }
            }
        }
        if (contributions.size() > 0) {
            AggregateHistogramContribution.Builder paddingContribution =
                    new AggregateHistogramContribution.Builder();
            if (mFlags.getMeasurementEnableFlexibleContributionFiltering()) {
                paddingContribution.setPaddingContributionWithFilteringId();
            } else {
                paddingContribution.setPaddingContribution();
            }
            padContributions(contributions, paddingContribution.build());
            return Optional.of(contributions);
        }
        return Optional.empty();
    }

    /**
     * Given a list of {@link AggregateHistogramContribution} actual contributions and a single
     * {@link AggregateHistogramContribution} padding contribution, append the maximum number of
     * padding contributions to the actual attributions, in place. The maximum number of
     * contributions is defined in the flags. If the number of actual contributions is already at
     * the maximum limit, then do nothing.
     *
     * @param contributions actual contributions
     * @param padding the contribution that will act as the pad value.
     */
    public void padContributions(
            List<AggregateHistogramContribution> contributions,
            AggregateHistogramContribution padding) {
        IntStream.range(
                        contributions.size(),
                        mFlags.getMeasurementMaxAggregateKeysPerSourceRegistration())
                .forEach(i -> contributions.add(padding));
    }

    /**
     * Returns first matched value map from getValueConfigs against Source filters or value map from
     * getValues.
     */
    public Optional<Map<String, AggregatableKeyValue>> getMatchedAggregatableKeyValueMap(
            AggregatableAttributionTrigger aggregatableAttributionTrigger,
            FilterMap sourceFilterMap,
            Filter filter) {
        if (aggregatableAttributionTrigger.getValueConfigs() != null) {
            for (AggregatableValuesConfig aggregatableValuesConfig :
                    aggregatableAttributionTrigger.getValueConfigs()) {
                boolean matchedFilters =
                        aggregatableValuesConfig.getFilterSet() == null
                                ? true
                                : filter.isFilterMatch(
                                        sourceFilterMap,
                                        aggregatableValuesConfig.getFilterSet(),
                                        true);
                if (!matchedFilters) {
                    continue;
                }
                boolean matchedNotFilters =
                        aggregatableValuesConfig.getNotFilterSet() == null
                                ? true
                                : filter.isFilterMatch(
                                        sourceFilterMap,
                                        aggregatableValuesConfig.getNotFilterSet(),
                                        false);
                if (matchedNotFilters) {
                    return Optional.of(aggregatableValuesConfig.getValues());
                }
            }
        }
        return Optional.empty();
    }

    /** Add a new contribution with key, value to the existing list of contributions. */
    private static AggregateHistogramContribution buildContribution(BigInteger key, int value) {
        return new AggregateHistogramContribution.Builder().setKey(key).setValue(value).build();
    }

    /** Add a new contribution with key, value,and id to the existing list of contributions. */
    private static AggregateHistogramContribution buildContribution(
            BigInteger key, int value, UnsignedLong filteringId) {
        return new AggregateHistogramContribution.Builder()
                .setKey(key)
                .setValue(value)
                .setId(filteringId)
                .build();
    }

    /** Returns the API version for the report. */
    public static String getApiVersion(Flags flags) {
        if (flags.getMeasurementEnableFlexibleContributionFiltering()) {
            return POST_FLEXIBLE_CONTRIBUTION_FILTERING_API_VERSION;
        }
        return PRE_FLEXIBLE_CONTRIBUTION_FILTERING_API_VERSION;
    }
}
