#!/usr/bin/env python
#
# Copyright (C) 2022 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import xml.etree.ElementTree as ET
import datetime
import os

# This script generates and updates the public.xml file for adservices apk automatically.
# Must be run after adding new strings to adservices apk.

PUBLIC_RES_FILE = '../apk/publicres/values/public.xml'
STRING_FILE = '../apk/res/values/strings.xml'
COPYRIGHT_TEXT = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (C) {datetime.date.today().year} The Android Open Source Project

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!-- DO NOT MODIFY. This file is automatically generated by generate_adservices_public_xml.py -->
'''
# Selecting 0x7f017fff as the starting identifier if no public.xml
STARTING_ID = '0x7f017fff'

public_xml = ET.Element('resources')
cur_id = int(STARTING_ID, 16)
existing_strings = set()
# we preserve existing IDs for backwards compatibility
if os.path.exists(PUBLIC_RES_FILE):
    public_xml = ET.parse(PUBLIC_RES_FILE).getroot()
    cur_id = int(public_xml[-1].attrib['id'], 16) - 1
    existing_strings = set(x.attrib['name'] for x in public_xml)
strings_xml = ET.parse(STRING_FILE).getroot()
for x in strings_xml:
    if x.attrib['name'] in existing_strings:
        continue
    cur_element = ET.SubElement(public_xml, 'public')
    cur_element.set('type', 'string')
    cur_element.set('name', x.attrib['name'])
    cur_element.set('id', hex(cur_id))
    cur_id -= 1

ET.indent(public_xml, space='    ')
if os.path.exists(PUBLIC_RES_FILE):
    os.remove(PUBLIC_RES_FILE)
with open(PUBLIC_RES_FILE, 'w') as f:
    f.write(COPYRIGHT_TEXT)
    f.write(ET.tostring(public_xml, encoding="unicode"))
